### ISSUE TITLE
image should never be the URL to the generic "missing photo" image

### ISSUE THREAD

**Issue by mhl** [everypolitician-scrapers/nigeria-national-assembly#10]
At the moment a number of people have http://www.nass.gov.ng/images/mps/avatar.jpg in their `image` column, which is of very little use to most users of the scraped data - it's generally more helpful to know that the image is missing so you can handle that case yourself, so we should set the `image` column to `NULL` or `''` in those cases.

**Comment by tmtmtmtm** [comment]
Skipping this would also mean that an image from a later source could become the primary image for the person.

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/everypolitician-scrapers/nigeria-national-assembly/pull/11
